---
namespace: "tcharl"
name: "acme_ingress"
version: "1.0.1"
description: "Bridges the gap between Cert-manager and Freeipa ACME server"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/acme_ingress"
documentation: "https://github.com/OsgiliathEnterprise/acme_ingress/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/acme_ingress"
issues: "https://github.com/OsgiliathEnterprise/acme_ingress/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "freeipa"
  - "cert-manager"
