---
- name: Converge master
  hosts: master.osgiliath.test
  vars:
    secure_logs: False
    kube_firewall_zone: 'public'
    standalone_role: False
    reset_kube: True
    preferred_nic: "eth1"
    company_domain: osgiliath.test
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
  roles:
    - role: tcharl.acme_ingress
